{
 "title": "GraphQL API",
 "description": "Example dashboard for metrics provided by yabeda-graphql gem for monitoring of APIs powered by GraphQL-Ruby.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Field resolve time (95th percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(graphql_field_resolve_runtime_seconds_bucket[1m])) by (type,field,le))",
     "legendFormat": "{{type}}.{{field}}"
    }
   ]
  },
  {
   "title": "Queries throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(graphql_query_fields_count[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Mutations throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(graphql_mutation_fields_count[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Deprecated fields usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(graphql_fields_request_count{deprecated=\"true\"}[1m])) by (type, field)",
     "legendFormat": "{{type}}.{{field}}"
    }
   ]
  }
 ]
}